### ISSUE TITLE
.dict/.data pairs (NIS_Intro) other than global error

### ISSUE THREAD

**Issue by Julian0555** [Joschuka/fmt_lm3#1]
I haven't had any luck getting it to load models from Hotel/NIS_Intro.dict, although it works perfectly fine for the global models. The way the original post is worded gave me the impression that this should be feasible but I keep getting errors. Is this something that can be added/fixed? In particular, I am interested in getting Peach's model, which I know is in NIS_Intro. 

![python](https://user-images.githubusercontent.com/64396108/87256284-03e02f00-c446-11ea-96c8-7a3dd6987a10.PNG)

**Comment by Joschuka** [comment]
I can't reproduce the error, the extraction and previewing of the assets of the "non global" pairs work fine for me, including the one you mentioned. 
Can you tell me the exact steps to reproduce the issue ?

**Comment by Julian0555** [comment]
I went through all of the steps a fourth time and somehow it worked fine on this attempt. Not quite sure what happened before. Sorry about that. Thank you for responding.

**Comment by Joschuka** [comment]
No problems, glad you solved it. If that happens again feel free to reopen the issue.
